version: "3.3"
services:
  saigon4paws:
    build:
      context: ./Saigon4Paws
      dockerfile: Dockerfile
    volumes:
      - /home/s4p-uploads:/home/s4p-uploads
    restart: always
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - saigon4paws